# -*- coding: utf-8 -*-
"""bitfinexfetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAFBVY93LhLlfuvyoGkEBgMf4cdpSRz-

https://docs.bitfinex.com/reference/rest-public-trades\

WHILE LOOP
"""

import pandas as pd
import requests

def fetch_bitfinex_historical_data(symbol, start_timestamp, end_timestamp, limit=10000):
      all_data = []

      while start_timestamp < end_timestamp:
              # Calculate the end timestamp for this chunk
              chunk_end = min(start_timestamp + (limit * 60000), end_timestamp)

              # Construct the URL
              url = f"https://api-pub.bitfinex.com/v2/trades/tBTCUSD/hist?limit={limit}&start={start_timestamp}&end={chunk_end}"

              # Fetch data from the API
              response = requests.get(url)
              data = response.json()
              all_data.extend(data)


              # Update start timestamp for the next chunk
              start_timestamp = chunk_end

      return all_data

start_timestamp = 1709251199000  ###Thursday, February 29, 2024 11:59:59 PM
end_timestamp = 1715601599000   #Monday, May 13, 2024 11:59:59 AM
#end_timestamp = 1709258399000   #Friday, March 1, 2024 1:59:59 AM
#end_timestamp = 1710331199000    #Wednesday, March 13, 2024 11:59:59 AM
limit=10000

historical_data = fetch_bitfinex_historical_data(limit, start_timestamp, end_timestamp)

df = pd.DataFrame(historical_data, columns=['ID', 'timestamp', 'amount', 'price'])
df.to_csv('Bitfinex_timestamp.csv', index=False)

print(historical_data[0:3])

# Convert data to DataFrame
df = pd.DataFrame(all_data, columns=['ID', 'timestamp', 'amount', 'price'])
df['timestamp'] = pd.to_datetime(df['timestamp'],unit= 'ms')
#df.to_csv('out1.csv', index=False)
print(df)